### ISSUE TITLE
IE9 - header menus position issue

### ISSUE THREAD

**Issue by alexandery** [angular-ui/ng-grid#2319]
When opening popup header menus in IE9 (sorting, export) the menus popup in random areas on the screen. To fix that - override the CSS:

```css
.ui-grid-menu {
	position: absolute;
}
```
