### ISSUE TITLE
Conditional Row Formatting?

### ISSUE THREAD

**Issue by bazeli** [angular-ui/ng-grid#2448]
Is it possible to apply conditional row formatting based on gridOptions.data values?  Specifically, I need to apply a style to a non consecutive series of rows based on a column's value (ex: if the column was a date, color the row if the date is within 2 days of the current date)

I would think this might be a common task that many would need to implement, but couldn't find the appropriate documentation in the Tutorial (which is otherwise quite helpful!).

**Comment by furier** [comment]
:+1: I'm looking for the same thing. I want to add a css class to a row based on the value in one of the columns.

**Comment by doshimehul** [comment]
Hi Guys,

I am doing something similar but with rowTemplate

///////////////////

function rowTemplate() {
            return $timeout(function() {
                return '<div ng-class="{strike: getExternalScopes().checkStatus(row)}"  ng-repeat="col in colContainer.renderedColumns track by col.colDef.name" class="ui-grid-cell" ui-grid-cell></div>';
            }, 1000);
        }
///////////////////

$scope.gridOptions['rowTemplate'] = rowTemplate();

//////////////////////////

.strike {
    background-color: lightgrey !important;
}

**Comment by PaulL1** [comment]
I've tried a few ways to do this in the base code, and there are limitations that are getting in my way.  The best way to achieve it turns out to be just changing the rowTemplate, which is easy and very configurable.

I've updated the tutorial http://ui-grid.info/docs/#/tutorial/317_custom_templates to show how, it will come through when I next push.

**Comment by NilsEngelbach** [comment]
Hey @PaulL1,

why isn't it possible to provide a function like rowStyle(row) in the options. The function would be taking the row as argument and return the style classes based on the row.entities.
Then in the default rowTemplate you could add somethin like ng-class="grid.options.rowStyle(row)".

I already did a Plunker:
http://embed.plnkr.co/DO7YFUuuPpdN5SDRewr8/preview

Wouldn't that be a good solution?

**Comment by bborowin** [comment]
+1 to rowStyle, we already have cellStyle, this only makes sense

**Comment by JasonCust** [comment]
An interim workaround would be to use CSS. Apply the desired classname (e.g. `CELL_CLASS_NAME`) to the first cell in the row (this is crucial) and the following selector:

```css
.ui-grid-row .ui-grid-cell.CELL_CLASS_NAME, .ui-grid-row .ui-grid-cell.CELL_CLASS_NAME ~ .ui-grid-cell {
  background-color: lightsteelblue;
}
```

The magic is the second selector that uses the [general sibling selector](https://developer.mozilla.org/en-US/docs/Web/CSS/General_sibling_selectors) to select the rest of the cells in the row. This is why it is important to set the cell class on the first cell of the row. The general sibling selector can only select siblings that are next in the DOM and not preceding it. Hence why sibling selectors are referred to as [_Following-sibling combinators_](https://drafts.csswg.org/selectors-4/#general-sibling-combinators) in the spec.

Note: the preceding style would apply to the row whether or not if it was selected. To only apply to non-selected rows the selector would need to include the pseudo class for [`:not`](https://developer.mozilla.org/en-US/docs/Web/CSS/:not).

```css
.ui-grid-row:not(.ui-grid-row-selected) .ui-grid-cell.CELL_CLASS_NAME, .ui-grid-row:not(.ui-grid-row-selected) .ui-grid-cell.CELL_CLASS_NAME ~ .ui-grid-cell {
  background-color: lightsteelblue;
}
```
