### ISSUE TITLE
enableRowHeaderSelection hides filters

### ISSUE THREAD

**Issue by nattro** [angular-ui/ng-grid#2768]
Setting:
**enableRowHeaderSelection : true**
with 
**enableFiltering: true**
causes header height to become fixed and not display filters.
Using css to expand the header will display the filters:
```css
    .ui-grid-header-cell {
        height: 57px;
        max-height: 57px;
    }
```
I'm assuming that this is not intentional.
