### ISSUE TITLE
With filtering enabled, selection checkboxes dont line up.

### ISSUE THREAD

**Issue by joshribakoff** [angular-ui/ng-grid#3555]
If both filtering & selecting is enabled, I see this:
![selection_602](https://cloud.githubusercontent.com/assets/4021306/7757456/5a9b7d4e-ffb7-11e4-9406-b5358ad95820.png)

I'm doing a workaround for now
```css

.ui-grid-header-cell {
    height:60px;
}
```

![selection_603](https://cloud.githubusercontent.com/assets/4021306/7757465/6df5e046-ffb7-11e4-8d90-e1de4992c93e.png)
